99_cats/cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, only: [:index, :show, :edit, :update, :create, :new]
  resources :cat_rental_requests, only: [:show, :new, :create]
end

99_cats/cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

99_cats/cats/app/models/cat.rb
require 'action_view'
class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper
    CAT_COLORS = ['orange', 'brown', 'grey', 'white', 'black', 'beige']

    validates :name, :birthdate, :description, presence: true
    validates :color, inclusion: CAT_COLORS, presence: true
    validates :sex, inclusion: ['M', 'F'], presence: true

    has_many :rentals,
        foreign_key: :cat_id,
        class_name: :CatRentalRequest,
        dependent: :destroy

    def age
        #time_ago_in_words(self.birthdate)
        Time.now.year - birthdate.year
    end
end

99_cats/cats/app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord 
    validates :cat_id, :start_date, :end_date, presence: true 
    validates :status, inclusion: [ 'PENDING', 'APPROVED', 'DENIED'], presence: true
    validates :does_not_overlap_approved_request, acceptance: true

    belongs_to :cat,
        foreign_key: :cat_id,
        class_name: :Cat 

    def overlapping_requests
        CatRentalRequest
            .where(cat_id: self.cat_id)
            .where.not(id: self.id)
            .where('(start_date <= :end_date AND start_date >= :start_date) OR (end_date <= :end_date AND end_date >= :start_date)', end_date: end_date, start_date: start_date )
            
            
    end

    def overlapping_approved_requests
        overlapping_requests.where("status = 'APPROVED'")
    end

    def does_not_overlap_approved_request
        !overlapping_approved_requests.exists?
    end






end

99_cats/cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

99_cats/cats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

    def show
        @cat_rental = CatRentalRequest.find(params[:id])
        render :show
    end

    def new 
        @cat_rental = CatRentalRequest.new
        render :new
    end

    def create 
        @cat_rental = CatRentalRequest.new(rental_params)
        if @cat_rental.save
            redirect_to cat_rental_request_url(@cat_rental)
        else
            render json: @cat_rental.errors.full_messages, status: 422
        end


    end


    private
    def rental_params
        params.require(:cat_rental).permit(:cat_id, :start_date, :end_date)

    end



end

99_cats/cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

    def index
        @cats = Cat.all
        render :index
    end

    def show
        @cat = Cat.find(params[:id])
        render :show

    end

    def new
        @cat = Cat.new
        render :new
    end

    def create 
        @cat = Cat.new(cat_params)
        if @cat.save 
            redirect_to cat_url(@cat)
        else
            render json: @cat.errors.full_messages, status: 422
        end
    end

    def edit
        @cat = Cat.find(params[:id])
        render :edit
    end

    def update
        @cat = Cat.find(params[:id])

        if @cat.update(cat_params)
            redirect_to cat_url(@cat)
        else
            render json: @cat.errors.full_messages, status: 422
        end
    end

    private
    def cat_params
        params.require(:cat).permit(:name, :birthdate, :color, :sex, :description)
    end
end

99_cats/cats/app/helpers/application_helper.rb
module ApplicationHelper
end

99_cats/cats/app/views/cat_rental_requests/_form.html.erb
<% if action == :edit %>
  <% action_url = cat_rental_request_url(cat_rental)%>
<% else %>
  <% action_url = cat_rental_requests_url %>
<% end %>

<form action="<%= action_url %>" method="post">
    <% if action == :edit && cat_rental.persisted? %>
        <input type="hidden" name="_method" value="PATCH">
    <% end %>

    <label for="cat_id">Cat ID:
        <input type="text" id="cat_id" name="cat_rental[cat_id]" value="<%= cat_rental.cat_id %>">
    </label>
    <br>

    <label for="start_date">Start Date:
        <input type="date" id="start_date" name="cat_rental[start_date]"value="<%= cat_rental.start_date %>">
    </label>

    <br>

    <label for="end_date">End Date:
        <input type="date" id="end_date" name="cat_rental[end_date]"value="<%= cat_rental.end_date %>">
    </label>

    <br>

    
    <input type="submit" value=<%= action == :edit ? 'Edit a cat_rental' : 'Add a cat_rental' %>>

99_cats/cats/app/views/cat_rental_requests/new.html.erb
<h1>Cat Rental</h1>

<%= render 'form', cat_rental: @cat_rental, action: :new %>

99_cats/cats/app/views/cat_rental_requests/show.html.erb
<table>
        <thead>
            <tr>
                <th colspan="2">Cat Request</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>ID</td>
                <td><%= @cat_rental.id %></td>
            </tr>
            <tr>
                <td>Cat ID</td>
                <td><%= @cat_rental.cat_id%></td>
            </tr>
            <tr>
                <td>Start Date</td>
                <td><%= @cat_rental.start_date %></td>
            </tr>
            <tr>
                <td>End Date</td>
                <td><%= @cat_rental.end_date %></td>
            </tr>
        </tbody>
    </table>

99_cats/cats/app/views/cats/_form.html.erb
<% if action == :edit %>
  <% action_url = cat_url(cat)%>
<% else %>
  <% action_url = cats_url %>
<% end %>

<form action="<%= action_url %>" method="post">
    <% if action == :edit && cat.persisted? %>
        <input type="hidden" name="_method" value="PATCH">
    <% end %>

    <label for="name">Name:
        <input type="text" id="name" name="cat[name]" value="<%= cat.name %>">
    </label>
    <br>

    <label for="birthdate">Birthdate:
        <input type="date" id="birthdate" name="cat[birthdate]"value="<%= cat.birthdate %>">
    </label>

    <br>

    <label for="color">Color</label>
    <select name="cat[color]" id="color">
        <option disabled <%= cat.color ? '' : 'selected' %>>--Please Select--</option>
        <option value="orange" <%= cat.color == 'orange' ? 'selected' : "" %>>orange</option>
        <option value="brown" <%= cat.color == 'brown' ? 'selected' : "" %>>brown</option>
        <option value="grey"<%= cat.color == 'grey' ? 'selected' : "" %>>grey</option>
        <option value="white"<%= cat.color == 'white' ? 'selected' : "" %>>white</option>
        <option value="black"<%= cat.color == 'black' ? 'selected' : "" %>>black</option>
        <option value="beige"<%= cat.color == 'beige' ? 'selected' : "" %>>beige</option>
    </select>

    <br>

    <label for="sex">Sex</label>
    <select name="cat[sex]" id="sex">
        <option disabled <%= cat.sex ? '' : 'selected' %>>--Please Select--</option>
        <option value="M"<%= cat.sex == 'M' ? 'selected' : "" %>>M</option>
        <option value="F"<%= cat.sex == 'F' ? 'selected' : "" %>>F</option>
    </select>

    <br>

    <label for="description">Description</label>
    <textarea name="cat[description]" id="description" >
        <%= cat.description %>
    </textarea>
    
    <input type="submit" value=<%= action == :edit ? 'Edit a cat' : 'add a cat'%>>

99_cats/cats/app/views/cats/edit.html.erb
<h1>Edit a cat!</h1>

<!-- action: url to which we want to send data -->
<!-- method: http method that we want to use -->

<%= render 'form', cat: @cat, action: :edit %>

99_cats/cats/app/views/cats/index.html.erb
<h1> All the cats </h1>

<ul>
    <% @cats.each do |cat| %>
        <li><%= cat.id %></li>
        <li><%= cat.name%></li>
        <li><a href="<%= cat_url(cat) %>">Show Cat</a></li>
        <br>
    <% end  %>
</ul>

99_cats/cats/app/views/cats/new.html.erb
<form action="<%= cats_url %>" method="post">
    <label for="name">Name:
        <input type="text" id="name" name="cat[name]">
    </label>
    <br>

    <label for="birthdate">Birthdate:
        <input type="date" id="birthdate" name="cat[birthdate]">
    </label>

    <br>

    <label for="color">Color</label>
    <select name="cat[color]" id="color">
        <option disabled selected>--Please Select--</option>
        <option value="orange">orange</option>
        <option value="brown">brown</option>
        <option value="grey">grey</option>
        <option value="white">white</option>
        <option value="black">black</option>
        <option value="beige">beige</option>
    </select>

    <br>

    <label for="sex">Sex</label>
    <select name="cat[sex]" id="sex">
        <option disabled selected>--Please Select--</option>
        <option value="M">M</option>
        <option value="F">F</option>
    </select>

    <br>

    <label for="description">Description</label>
    <textarea name="cat[description]" id="description" ></textarea>

    <input type="submit" value="Add a cat">


    
    
    
    
    
    








</form>

99_cats/cats/app/views/cats/show.html.erb
    <table>
        <thead>
            <tr>
                <th colspan="2"><%= @cat.name.capitalize %></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Age:</td>
                <td><%= @cat.age %></td>
            </tr>
            <tr>
                <td>Color:</td>
                <td><%= @cat.color %></td>
            </tr>
            <tr>
                <td>Sex:</td>
                <td><%= @cat.sex %></td>
            </tr>
            <tr>
                <td>Description:</td>
                <td><%= @cat.description %></td>
            </tr>
        </tbody>
    </table>

99_cats/cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

99_cats/cats/app/views/layouts/cats/index.html.erb
<h1> All the cats </h1>

<ul>
    <% @cats.each do |cat| %>
        <%= render cat %>
    <% end %>
</ul>